### ISSUE TITLE
Stack support?

### ISSUE THREAD

**Issue by aljce** [ucsd-progsys/liquid-types-spacemacs#1]
I use stack for all my projects which also means I don't install libraries or executable globally. This means that when trying to use the spacemacs layer liquid types I get the following error:

``` sh
Syntax checker in buffer Unique.hs in haskell-mode:

  haskell-liquid
    - major mode: `haskell-mode' supported
    - predicate:  nil
    - executable: Not found

Flycheck cannot use this syntax checker for this buffer.

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.
```

The new executable control flow could look like this:
Is there a global liquid haskell executable?
- Yes -> use that (this keeps old behavior)
- No -> is there a stack.yaml?
  - No -> error with the above error
  - Yes -> test `stack exec liquid`
    - executable exists -> use the command `stack exec liquid` to check buffers
    - executable doesn't exist -> error with the above error

I would be happy to put together a pr if I was pointed in the direction of where spacemacs looks for the liquid haskell executable.

**Comment by ranjitjhala** [comment]
Hi @mckeankylej -- a PR for this would be fantastic! The layer looks for the executable here:

https://github.com/ucsd-progsys/liquid-types-spacemacs/blob/master/extensions/flycheck-liquid/flycheck-liquid.el#L44

That is, currently it just assumes there is something called `"liquid"` that is in the path and runs it.
I think what we'd want is to use the above logic to generate the appropriate string `liquid` or `stack exec -- liquid` for the `:command` field, e.g. as done here:

https://github.com/flycheck/flycheck-hdevtools/blob/master/flycheck-hdevtools.el#L44-L54

Does that help? 

Thanks!

https://github.com/flycheck/flycheck-hdevtools/blob/master/flycheck-hdevtools.el#L44-L54

**Comment by aljce** [comment]
Yes this helps immensely I will get right on this.

**Comment by aljce** [comment]
Turns out because I use intero layer instead of the haskell layer I cant get this to work. This being said I doubt you guys will support intero?

**Comment by ranjitjhala** [comment]
I think the dependencies on the Haskell layer are minimal (or non existent
so it should be possible to add this to the intero layer too...

**Comment by aljce** [comment]
Okay I will look deeper into whats giving me the errors.

**Comment by ranjitjhala** [comment]
The dependency on the Haskell layer is for the Haskell-mode-hook (which is
used to activate the flycheck-liquid). There must be an intero-mode-hook
that can be used instead?

**Comment by aljce** [comment]
This is becoming irrelevant intero is becoming a backend for haskell-mode. Any objections to me closing this and the associated PR?

**Comment by ranjitjhala** [comment]
Sounds good -- intero is just absolutely awesome!!
